#----------------------------------------------------------------------------------------------------
# Light Controls
- alias: Living Room Lamp On at Sunset
  # Turns on the living Room Lamp shortly before sunset
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  action:
  - service: light.turn_on
    entity_id: light.philips_lwb014_dba18b02_level_on_off
- alias: Living Room Lamp Off at Bedtime
  # Lamp turns off at night, but makes sure we're not listening to music or tv first
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.lvng_rm_lamp_off_time.state[0:5] }}"
  condition: 
  - condition: state
    entity_id: media_player.living_room
    state: 'paused'
  action:
  - service: light.turn_off
    entity_id: light.philips_lwb014_dba18b02_level_on_off    
- alias: Living Room Lamp Off Night After Media Off
  # Lamp turns off a bit after turning off sonos/tv if it's after sunset 
  trigger:
  - platform: state
    entity_id: media_player.living_room
    from: 'playing'
    to: 'paused'
    for: "00:15:00"
  condition: 
  - condition: sun
    after: sunset
  - condition: state
    entity_id: light.philips_lwb014_dba18b02_level_on_off 
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.philips_lwb014_dba18b02_level_on_off    
- alias: Porch Lights On at Sunset
  # Porch lights come on shortly before sunset
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  action:
  - service: switch.turn_on
    entity_id: switch.jasco_products_unknown_type_4952_id_3135_switch    
- alias: Porch Lights Off at Sunrise
  # Porch lights turn off at sunrise
  trigger:
  - event: sunrise
    platform: sun
  action:
  - service: switch.turn_off
    entity_id: switch.jasco_products_unknown_type_4952_id_3135_switch    
- alias: Patio Lights Turn On When Back Door Opens
  # Turns on patio lights when back door opens at night
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_0f4f2104_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.jasco_products_unknown_type_4944_id_3235_level_2
    state: 'off'
  - after: sunset
    condition: sun
  action:
  - service: light.turn_on
    entity_id: light.jasco_products_unknown_type_4944_id_3235_level_2    
#----------------------------------------------------------------------------------------------------
# Alarm Notifications
- alias: Actionable Notification Alarm Arm 
  # After media off and alarm didn't auto-arm, because staying up late, send actionable notification
  trigger:
  - platform: state
    entity_id: media_player.living_room
    from: 'playing'
    to: 'paused'
  condition: 
  - condition: template
    value_template: "{{ states.sensor.time.state > states.input_datetime.alarm_auto_arm_time.state[0:5] }}" 
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'off'
  action:
    service: notify.notify_all_phones
    data:
      title: "Arm Alarm Now?"
      message: "Swipe Left->View (lockscreen) or Down (popup)"
      data:
        push:
          category: "alarm" # Needs to match the top level identifier used in the ios configuration
- alias: Door Open Alarm Utility
  # Utility Room Door Open Alert Alarm/Critical Notification
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_84562104_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - data:
      variables:
        message: >
          {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_84562104_on_off', 'on' %}
            Utility Room Door Open
          {% endif %}
        title: Door Open!
    entity_id: script.phone_critical_alert
    service: script.turn_on
  - service: scene.turn_on
    entity_id: scene.alarm_alert_scene
  - data:
      variables:
        message: >
          {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_84562104_on_off', 'on' %}
            Utility Room Door Open!
          {% endif %}
        volume: 0.4
    entity_id: script.sonos_say_to_all
    service: script.turn_on
- alias: Door Open Alarm Front
  # Front Door Open Alert Alarm/Critical Notification
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_4c572104_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - data:
      variables:
        message: Front Door Open
        title: Door Open!
    entity_id: script.phone_critical_alert
    service: script.turn_on
  - service: scene.turn_on
    entity_id: scene.alarm_alert_scene
  - data:
      variables:
        message: Front Door Open!
        volume: 0.4
    entity_id: script.sonos_say_to_all
    service: script.turn_on
- alias: Door Open Alarm Back
  # Back Door Open Alert Alarm/Critical Notification
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_0f4f2104_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - data:
      variables:
        message: Back Door Opened
        title: Door Open!
    entity_id: script.phone_critical_alert
    service: script.turn_on
  - service: scene.turn_on
    entity_id: scene.alarm_alert_scene
  - data:
      variables:
        message: Back Door Open!
        volume: 0.4
    entity_id: script.sonos_say_to_all
    service: script.turn_on
- alias: Door Open Alarm Side
  # Side Door Open Alert Alarm/Critical Notification
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_8edf0b04_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - data:
      variables:
        message: Garage Side Door Opened
        title: Door Open!
    entity_id: script.phone_critical_alert
    service: script.turn_on
  - service: scene.turn_on
    entity_id: scene.alarm_alert_scene
  - data:
      variables:
        message: Garage Side Door Open!
        volume: 0.4
    entity_id: script.sonos_say_to_all
    service: script.turn_on
#----------------------------------------------------------------------------------------------------
# Alarm Arm/Disarm Controls
- alias: Arm Alarm from Notification
  # Actionable Notification Alarm Arm sends event that triggers this automation
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ARM_ALARM
  action:
  - data: {}
    entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_on
- alias: Arm Alarm at Night
  # Arm alarm at time set in UI, only fires if Living Room Lamp is off
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.alarm_auto_arm_time.state[0:5] }}"
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'off'
  - condition: state
    entity_id: light.philips_lwb014_dba18b02_level_on_off
    state: 'off'
  action:
  - data: {}
    entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_on
- alias: Disarm Alarm in Morning
  # Disarms alarm in the morning at time set in UI
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.alarm_auto_disarm_time.state[0:5] }}"
  condition: 
  action:
  - data: {}
    entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_off
- alias: Arm Alarm and Set TStat When Gone
  # Arm alarm and set TStat to away when we're both away from home
  trigger:
  - entity_id: group.peopleanyonehome
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_on
  - data:
      preset_mode: away
    entity_id: climate.thermostat
    service: climate.set_preset_mode
- alias: Disarm Alarm Set TStat When Anyone Returns
  # Disarms alarm, runs TStat schedule when someone/anyone/all come home
  trigger:
  - entity_id: group.peopleanyonehome
    from: not_home
    platform: state
    to: home
    # Note the above group changes to home when either or both are home
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_off
  - data:
      preset_mode: none
    entity_id: climate.thermostat
    service: climate.set_preset_mode
- alias: Arm Alarm with Noisemaker
  # Arm alarm when noisemaker plug is switched on (backup in case it didn't auto arm)
  trigger:
  - entity_id: switch.ledvance_plug_e2161100_on_off
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'off'
  action:
  - entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_on
- alias: Disarm Alarm When Front Door Unlocked
  # Disarm alarm if front door is unlocked 
  trigger:
  - entity_id: lock.kwikset_spectrum_brands_unknown_type_0003_id_0238_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_off
  - data:
      variables:
        message: Alarm is disarmed. Have a great day!
        sonos_entity: media_player.office
        volume: 0.3
    entity_id: script.sonos_say
    service: script.turn_on
  - data:
      variables:
        message: Front Door Unlocked
        title: Alarm Disarmed
    entity_id: script.phone_notification
    service: script.turn_on
- alias: Arm Alarm When Front Door Locked
  # Arms alarm hen noisemaker is on, or all humans are away
  trigger:
  - entity_id: lock.kwikset_spectrum_brands_unknown_type_0003_id_0238_locked
    from: unlocked
    platform: state
    to: locked
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'off'
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.arm_alarm
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.ledvance_plug_e2161100_on_off
        state: 'on'
      - condition: state
        entity_id: group.peopleanyonehome
        state: not_home
  action:
  - entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_on
- alias: Disarm Alarm When Second Person Returns Late
  # Disarms alarm when one of us comes home after already armed
  trigger:
  - entity_id: group.peopleanyoneaway
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
  - entity_id: input_boolean.arm_alarm
    service: input_boolean.turn_off
#----------------------------------------------------------------------------------------------------
# Various Comfort and Maintenance Controls
- alias: Noisemaker Turn Off
  # Noisemaker turns off at time set in UI
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.noisemaker_off_time.state[0:5] }}"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - entity_id: switch.ledvance_plug_e2161100_on_off
    service: switch.turn_off
- alias: Camera Toggle With Alarm
#Toggles indoor cameras on-off in sync with Alarm Arm Switch
  trigger:
  - platform: state
    entity_id: input_boolean.arm_alarm
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.arm_alarm
    from: 'on'
    to: 'off'
  action:
    service_template: >
      {% if trigger.to_state.state == "on" %}
      switch.turn_on
      {% elif trigger.to_state.state == "off" %}
      switch.turn_off
      {% endif %}
    data_template: 
      entity_id: switch.ledvance_plug_e0611100_on_off     
#- alias: Camera Nightly Reboot
  # CURRENTLY DISABLED Reboots living room cameras nightly in order to prevent camera failure
  #trigger:
  #- platform: template
  #  value_template: "{{ states.sensor.time.state == states.input_datetime.camera_reset_time.state[0:5] }}"
  #condition: []
  #action:
  #- entity_id: switch.ledvance_plug_e0611100_on_off
  #  service: switch.turn_off
  #- delay:
  #    seconds: 30
  #- entity_id: switch.ledvance_plug_e0611100_on_off
  #  service: switch.turn_on
  