# Used to set default from the start, including frontend, important to keep
default_config:

# Included files/folders
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include_dir_named shell_command/

# Text to speech, used with Sonos
tts:
  - platform: google_translate

# Virtual camera to livestream a radar webpage
camera:
  - platform: generic
    still_image_url: https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/ustiw/animate.png
    content_type: image/gif
    name: regional doppler radar

# Garage Doors
cover:
  - platform: aladdin_connect
    username: !secret aladdin_user
    password: !secret aladdin_pass

# Custom switches
input_boolean:
  # Master alarm switch
  arm_alarm:
    name: Alarm Arm Switch
    initial: off
    icon: mdi:alarm
  # Used for Kiosk dashboard to make cards appear to move
  conditional_card_toggle:
    name: Conditional Card Toggle
    initial: on
    icon: mdi:filter-outline

# Sets usb location of Z Wave dongle
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml

# General notification to send to all phones at once
notify:
  - platform: group
    name: notify_all_phones
    services:
    - service: mobile_app_phone
    - service: mobile_app_caris_iphone

# Setup categories for Actionable Notifications
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'ARM_ALARM'
            title: 'Arm Alarm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'

# Used to allow for UI-based time/date inputs that automation runs on
input_datetime:
  camera_reset_time:
    name: Time Camera Reboot
    has_date: false
    has_time: true 
  lvng_rm_lamp_off_time:
    name: Time Living Room Lamp Off
    has_date: false 
    has_time: true 
  noisemaker_off_time:
    name: Time Noisemaker Off
    has_date: false 
    has_time: true 
  alarm_auto_arm_time:
    name: Time Alarm Auto Arm
    has_date: false 
    has_time: true 
  alarm_auto_disarm_time:
    name: Time Alarm Auto Disarm
    has_date: false 
    has_time: true 

sensor:
  #generates a sensor in HA that reflects current time and can be compared against in automation
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  #sun2 integration from: https://github.com/pnbruckner/ha-sun2 Left many options off for now
  - platform: sun2
    monitored_conditions:
      - sunrise
      - solar_noon
      - sunset
      - max_elevation
  #HA standard moon phase sensor
  - platform: moon

# Spotify Integration
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# LG TV Integration
wake_on_lan:

webostv:
  host: 10.0.0.211
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 20-17-42-36-58-52
      broadcast_address: 10.0.0.211

# Router Integration
device_tracker:
  - platform: tomato
    host: 10.0.0.2
    username: !secret tomato_user
    password: !secret tomato_password
    http_id: !secret tomato_http_id

# Bypassing entities that run often in logbook
logbook:
  exclude:
    entities:
      - input_boolean.conditional_card_toggle
      - automation.conditional_card_time_based_toggle
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
  include:
    entities:
      - sensor.front_door_lock_alarm_type
