# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Included files/folders
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include_dir_named shell_command/

# Text to speech
tts:
  - platform: google_translate
# Garage Doors
cover:
platform: aladdin_connect
    username: !secret aladdin_user
    password: !secret aladdin_pass
# Custom switch to arm alarm
input_boolean:
  arm_alarm:
    name: Alarm Arm Switch
    initial: off
    icon: mdi:alarm
# Thermostat connection
climate:
  - platform: honeywell
    username: !secret honeywell_user
    password: !secret honeywell_pass
    region: us 
    scan_interval: 600
    away_heat_temperature: 65
    away_cool_temperature: 74
# Sets usb location of Z Wave dongle
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml
# General notification for phones at once
notify:
  - platform: group
    name: notify_all_phones
    services:
    - service: mobile_app_phone
    - service: mobile_app_caris_iphone
input_datetime:
#Used to allow for UI-based time/date inputs that automation runs on
  camera_reset_time:
    name: Time Camera Reboot
    has_date: false
    has_time: true 
  lvng_rm_lamp_off_time:
    name: Time Living Room Lamp Off
    has_date: false 
    has_time: true 
  noisemaker_off_time:
    name: Time Noisemaker Off
    has_date: false 
    has_time: true 
  alarm_auto_arm_time:
    name: Time Alarm Auto Arm
    has_date: false 
    has_time: true 
  alarm_auto_disarm_time:
    name: Time Alarm Auto Disarm
    has_date: false 
    has_time: true 
sensor:
#generates a sensor in HA that reflects current time and can be compared against in automation
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
