# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  FinalTestBranchChangecase_url: morenohomeassistant.duckdns.org
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

cover:
  - platform: aladdin_connect
    username: !secret aladdin_user
    password: !secret aladdin_pass
input_boolean:
  arm_alarm:
    name: Alarm Arm Switch
    initial: off
    icon: mdi:alarm
climate:
  - platform: honeywell
    username: !secret honeywell_user
    password: !secret honeywell_pass
    region: us 
    scan_interval: 600
    away_heat_temperature: 65
    away_cool_temperature: 74
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml
notify:
  - platform: group
    name: notify_all_phones
    services:
    - service: mobile_app_phone
    - service: mobile_app_caris_iphone
input_datetime:
#Used to allow for UI-based time/date inputs that automation runs on
  camera_reset_time:
    name: time camera reset
    has_date: false
    has_time: true 
  lvng_rm_lamp_off_time:
    name: time lvng lamp off
    has_date: false 
    has_time: true 
sensor:
#generates a sensor in HA that reflects current time and can be compared against in automation
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'