# Kiosk View
title: Media
cch: 
  kiosk_mode: true
views:
  - title: Test
    path: test
    panel: true
    theme: black
    badges: []
    cards:
      - type: media-control
        entity: media_player.living_room