resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module

title: Media
views:
  - title: Test
    path: test
    panel: true
    theme: black
    badges: []
    cards:
      - type: media-control
        entity: media_player.living_room
      